[package]
name = "shelf"
description = "A command-line tool for managing dotfiles"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shelf"
path = "src/bin/main.rs"

[lib]
name = "shelf"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.12"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
clap = { version = "4.5.17", features = ["derive", "cargo"] }
dirs = "5.0.1"
tempfile = "3.12.0"
log = "0.4.22"
anyhow = "1.0.89"
dialoguer = "0.11.0"
shellexpand = "3.1.0"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
