[package]
name = "shlf"
description = "AI-based command-line tools for developers"
version = "0.8.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/ab22593k/shelf"

[lib]
name = "slf"

[[bin]]
name = "slf"
path = "src/main.rs"

[[bin]]
name = "gitai-hook"
path = "src/bin/hook.rs"

[dependencies]
git2 = "0.19"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
clap = { version = "4.5.17", features = ["derive", "cargo"] }
anyhow = "1.0.89"
dialoguer = "0.11.0"
shellexpand = "3.1.0"
clap_complete = "4.5.29"
colored = "2.1.0"
directories = "5.0.1"
home = "0.5.9"
rusqlite = "0.32.1"
chrono = "0.4.38"
walkdir = "2.5.0"
genai = "0.1.11"
async-trait = "0.1.83"
serde_json = "1.0.132"
reqwest = "0.12.9"
tempfile = "3.13.0"
indicatif = "0.17.8"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
