[package]
name = "shlf"
description = "A command-line tool for managing dotconf files"
version = "0.7.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/ab22593k/shelf"

[[bin]]
name = "slf"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
clap = { version = "4.5.17", features = ["derive", "cargo"] }
anyhow = "1.0.89"
dialoguer = "0.11.0"
shellexpand = "3.1.0"
clap_complete = "4.5.29"
colored = "2.1.0"
directories = "5.0.1"
home = "0.5.9"
rusqlite = "0.32.1"
chrono = "0.4.38"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
