[package]
name = "shlf"
description = "A command-line tool for managing config & dotfiles"
version = "0.6.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ab22593k/shelf"

[[bin]]
name = "slf"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
clap = { version = "4.5.17", features = ["derive", "cargo"] }
dirs = "5.0.1"
tempfile = "3.12.0"
log = "0.4.22"
anyhow = "1.0.89"
dialoguer = "0.11.0"
shellexpand = "3.1.0"
clap_complete = "4.5.29"
colored = "2.1.0"
directories = "5.0.1"
home = "0.5.9"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
